# Generated by Django 2.0.6 on 2018-08-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180827_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licores',
            name='marca',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='User',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Licores',
        ),
    ]
